// Hand-picked banks and apps shown on the board by default, keyed by our stable id.
// Values are the exact names NPCI uses, so the sync keeps these ids instead of generating new ones.
export const CURATED_NPCI = {
  sbi: "State Bank Of India",
  hdfc: "HDFC Bank",
  icici: "ICICI Bank",
  axis: "Axis Bank",
  kotak: "Kotak Mahindra Bank",
  pnb: "Punjab National Bank",
  bob: "Bank of Baroda",
  canara: "Canara Bank",
  union: "Union Bank Of India",
  idfc: "IDFC First Bank Ltd",
  yes: "Yes Bank Limited Ybs",
  indusind: "Indusind Bank",
  boi: "Bank of India",
  indian: "Indian Bank",
  iob: "Indian Overseas Bank",
  central: "Central Bank of India",
  uco: "UCO Bank",
  bom: "Bank of Maharashtra",
  psb: "Punjab And Sind Bank",
  au: "Au Small Finance Bank",
  federal: "Federal Bank",
  idbi: "IDBI Bank",
  rbl: "Ratnakar Bank Limited (RBL)",
  bandhan: "Bandhan Bank Limited",
  "south-indian": "The South Indian Bank Limited",
  karur: "Karur Vysya Bank",
  kbl: "Karnataka Bank",
  tmb: "Tamilnad Mercantile Bank Limited",
  "city-union": "City Union Bank",
  dcb: "DCB Bank Ltd",
  csb: "CSB Bank Limited",
  jk: "The Jammu & Kashmir Bank Limited",
  dhanlaxmi: "Dhanalakshmi Bank",
  equitas: "Equitas Small Finance Bank",
  ujjivan: "Ujjivan Small Finance Bank Limited",
  airtel: "Airtel Payments Bank Limited",
  ippb: "India Post Payments Bank Limited",
  "jio-pb": "Jio Payments Bank Ltd",
  fino: "Fino Payments Bank",
  hsbc: "HSBC Bank",
  sc: "Standard Chartered Bank",
};

// NPCI app names (lowercased) folded into our curated app ids.
export const CURATED_APP_NAMES = {
  gpay: "Google Pay",
  phonepe: "PhonePe",
  paytm: "Paytm",
  amazonpay: ["Amazon Pay", "Amazon"],
  cred: "CRED",
  navi: "Navi",
  whatsapp: "WhatsApp",
  mobikwik: "MobiKwik",
  supermoney: "super.money",
  flipkart: "Flipkart UPI",
  tataneu: "Tata Neu",
  bharatpe: "BharatPe",
  groww: "Groww",
  jupiter: "Jupiter Money",
  payzapp: "PayZapp",
};
