// Regenerates packages/shared/src/npci.generated.ts from data/npci-upi-members.json.
// Refresh the JSON from https://www.npci.org.in/api/all-members-tab-details?product_name=UPI&tab_name=<tab>&page_no=1&page_size=2000&locale=en
// for tabs: upi, 3rd-party-apps, ppi-apps.
import { readFileSync, writeFileSync } from "node:fs";
import { CURATED_NPCI, CURATED_APP_NAMES } from "./npci-curated.mjs";

const src = JSON.parse(readFileSync(new URL("../data/npci-upi-members.json", import.meta.url), "utf8"));

const clean = (s) =>
  s
    .replace(/\s+/g, " ")
    .replace(/^\(([^)]+)\)\s*/, "")
    .replace(/\s*\((android|ios|only android|android & ios)[^)]*\)/gi, "")
    .trim();

const STOP = new Set([
  "the", "of", "and", "&", "ltd", "ltd.", "limited", "pvt", "private", "co", "op", "operative", "cooperative",
  "bank", "india", "maryadit", "niyamit",
]);
const slug = (s) =>
  s
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-(limited|ltd)(?=-|$)/g, "")
    .replace(/^-|-$/g, "");

function short(name) {
  const words = name
    .replace(/[().,]/g, " ")
    .split(/[\s-]+/)
    .filter((w) => w && !STOP.has(w.toLowerCase()));
  const s = words.length === 1 ? words[0].slice(0, 5) : words.map((w) => w[0]).join("").slice(0, 5);
  return s.toUpperCase() || name.slice(0, 4).toUpperCase();
}

const curatedByNpci = new Map(Object.entries(CURATED_NPCI).map(([id, n]) => [n.toLowerCase(), id]));
const seen = new Set();
const banks = [];
const matched = new Set();

for (const [raw, details] of src.upi.rows) {
  if (details === "Acquirer") continue;
  const name = clean(raw);
  const curated = curatedByNpci.get(raw.replace(/\s+/g, " ").trim().toLowerCase());
  if (curated) matched.add(curated);
  let id = curated ?? slug(name);
  while (seen.has(id)) id += "-2";
  seen.add(id);
  banks.push({
    id,
    name,
    short: short(name),
    psp: details.startsWith("PSP"),
    ppi: details === "PSP & PPI Issuer",
  });
}

const missing = Object.keys(CURATED_NPCI).filter((id) => !matched.has(id));
if (missing.length) {
  console.error("Curated banks not found in NPCI list:", missing.join(", "));
  process.exit(1);
}

const appNames = new Map();
for (const [n] of src["3rd-party-apps"].rows) appNames.set(clean(n).toLowerCase(), clean(n));
for (const [, n] of src["ppi-apps"].rows) {
  const name = clean(n);
  if (!appNames.has(name.toLowerCase())) appNames.set(name.toLowerCase(), name);
}

const curatedApps = new Set(Object.values(CURATED_APP_NAMES).flat().map((n) => n.toLowerCase()));
const apps = [];
const appIds = new Set(Object.keys(CURATED_APP_NAMES));
for (const [key, name] of appNames) {
  if (curatedApps.has(key)) continue;
  let id = slug(name);
  while (appIds.has(id)) id += "-2";
  appIds.add(id);
  apps.push({ id, name });
}
apps.sort((a, b) => a.name.localeCompare(b.name));

const out = `// Generated by scripts/npci-sync.mjs from NPCI's UPI live members list. Do not edit by hand.
export const NPCI_SYNCED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};

export const NPCI_BANKS: { id: string; name: string; short: string; psp: boolean; ppi: boolean }[] = ${JSON.stringify(banks)};

export const NPCI_APPS: { id: string; name: string }[] = ${JSON.stringify(apps)};
`;
writeFileSync(new URL("../packages/shared/src/npci.generated.ts", import.meta.url), out);
console.log(`${banks.length} banks/PPIs (${banks.filter((b) => b.psp).length} PSP), ${apps.length} extra apps`);
